# recipe.yaml

{{ $imgname := or .imgname "dummy" }}

architecture: arm64

actions:
- action: recipe
  recipe: ./ospack.yaml
  variables:
    hostname: {{ $imgname }}

- action: recipe
  recipe: ./osvideopack.yaml

- action: recipe
  recipe: ./image.yaml
  variables:
    imgname: {{ $imgname }}
